// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	cart "projects/features/cart"

	mock "github.com/stretchr/testify/mock"
)

// CartData is an autogenerated mock type for the CartData type
type CartData struct {
	mock.Mock
}

// Add provides a mock function with given fields: userID, newCart
func (_m *CartData) Add(userID int, newCart cart.Core) (cart.Core, error) {
	ret := _m.Called(userID, newCart)

	var r0 cart.Core
	if rf, ok := ret.Get(0).(func(int, cart.Core) cart.Core); ok {
		r0 = rf(userID, newCart)
	} else {
		r0 = ret.Get(0).(cart.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, cart.Core) error); ok {
		r1 = rf(userID, newCart)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCartData interface {
	mock.TestingT
	Cleanup(func())
}

// NewCartData creates a new instance of CartData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCartData(t mockConstructorTestingTNewCartData) *CartData {
	mock := &CartData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
