// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	item "projects/features/item"

	mock "github.com/stretchr/testify/mock"
)

// ItemService is an autogenerated mock type for the ItemService type
type ItemService struct {
	mock.Mock
}

// Add provides a mock function with given fields: token, newItem
func (_m *ItemService) Add(token interface{}, newItem item.Core) (item.Core, error) {
	ret := _m.Called(token, newItem)

	var r0 item.Core
	if rf, ok := ret.Get(0).(func(interface{}, item.Core) item.Core); ok {
		r0 = rf(token, newItem)
	} else {
		r0 = ret.Get(0).(item.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, item.Core) error); ok {
		r1 = rf(token, newItem)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: token, itemID
func (_m *ItemService) Delete(token interface{}, itemID int) error {
	ret := _m.Called(token, itemID)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, int) error); ok {
		r0 = rf(token, itemID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllItems provides a mock function with given fields:
func (_m *ItemService) GetAllItems() ([]item.Core, error) {
	ret := _m.Called()

	var r0 []item.Core
	if rf, ok := ret.Get(0).(func() []item.Core); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]item.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetID provides a mock function with given fields: ItemID
func (_m *ItemService) GetID(ItemID int) (item.Core, error) {
	ret := _m.Called(ItemID)

	var r0 item.Core
	if rf, ok := ret.Get(0).(func(int) item.Core); ok {
		r0 = rf(ItemID)
	} else {
		r0 = ret.Get(0).(item.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(ItemID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MyItem provides a mock function with given fields: token
func (_m *ItemService) MyItem(token interface{}) ([]item.Core, error) {
	ret := _m.Called(token)

	var r0 []item.Core
	if rf, ok := ret.Get(0).(func(interface{}) []item.Core); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]item.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: token, itemID, updatedData
func (_m *ItemService) Update(token interface{}, itemID int, updatedData item.Core) (item.Core, error) {
	ret := _m.Called(token, itemID, updatedData)

	var r0 item.Core
	if rf, ok := ret.Get(0).(func(interface{}, int, item.Core) item.Core); ok {
		r0 = rf(token, itemID, updatedData)
	} else {
		r0 = ret.Get(0).(item.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, int, item.Core) error); ok {
		r1 = rf(token, itemID, updatedData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewItemService interface {
	mock.TestingT
	Cleanup(func())
}

// NewItemService creates a new instance of ItemService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewItemService(t mockConstructorTestingTNewItemService) *ItemService {
	mock := &ItemService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
